"""
reports.py — Report Generation & Audit Log API Routes

Endpoints:
  POST /api/reports/summary      — Generate a portfolio summary
  POST /api/reports/risk-note    — Generate a risk assessment note
  POST /api/reports/client-email — Draft a client email
  GET  /api/reports/audit-log    — View the full audit trail
"""

from typing import Optional

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.models.database import get_db
from app.models.schemas import ReportRequest, ReportResponse, AuditLogResponse
from app.services.report_generator import generate_report
from app.services.audit_logger import get_audit_logs

router = APIRouter()


@router.post("/summary", response_model=ReportResponse)
def create_summary(request: ReportRequest, db: Session = Depends(get_db)):
    """
    Generate a portfolio summary from uploaded documents.
    Includes executive overview, asset allocation, key holdings, and observations.
    """
    try:
        result = generate_report(
            db=db,
            report_type="summary",
            document_ids=request.document_ids,
            additional_instructions=request.additional_instructions,
        )
        return ReportResponse(**result)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/risk-note", response_model=ReportResponse)
def create_risk_note(request: ReportRequest, db: Session = Depends(get_db)):
    """
    Generate a risk assessment note from uploaded documents.
    Identifies concentration risk, market risk, liquidity concerns, and compliance flags.
    """
    try:
        result = generate_report(
            db=db,
            report_type="risk_note",
            document_ids=request.document_ids,
            additional_instructions=request.additional_instructions,
        )
        return ReportResponse(**result)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/client-email", response_model=ReportResponse)
def create_client_email(request: ReportRequest, db: Session = Depends(get_db)):
    """
    Draft a professional client email based on document content.
    Includes appropriate disclaimers and compliance language.
    """
    try:
        result = generate_report(
            db=db,
            report_type="client_email",
            document_ids=request.document_ids,
            additional_instructions=request.additional_instructions,
        )
        return ReportResponse(**result)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/audit-log", response_model=list[AuditLogResponse])
def view_audit_log(
    limit: int = 50,
    offset: int = 0,
    action_type: Optional[str] = None,
    db: Session = Depends(get_db),
):
    """
    View the audit trail of all LLM interactions.

    This endpoint is essential for compliance — it allows compliance officers
    to review every question asked, every document chunk retrieved, and
    every response generated by the AI.

    Filter by action_type: "chat_query", "report_summary", "report_risk_note", "report_client_email"
    """
    logs = get_audit_logs(db, limit=limit, offset=offset, action_type=action_type)
    return logs
